language: ruby
rvm:
  - 2.6.2
env:
  - DB=mysql
sudo: required
services:
  - mysql
addons:
  chrome: stable
before_install: gem install bundler
install:
  - wget -N https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
  - cp test/travisconfig/database.yml config/database.yml
  - cp test/travisconfig/secrets.yml config/secrets.yml
  - mysql -e 'create database greasyforktest'
  - mysql greasyforktest < db/structure.sql
script:
  - bundle install
  - bundle exec rake test test:system
