aws:
  service: S3
  access_key_id: <%= Rails.application.secrets.aws&.[](:access_key_id) %>
  secret_access_key: <%= Rails.application.secrets.aws&.[](:secret_access_key) %>
  bucket: <%= Rails.application.secrets.aws&.[](:bucket) %>
  region: <%= Rails.application.secrets.aws&.[](:region) %>
  public: true

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
